import jsPDF from "jspdf";

export interface ComplaintReportItem {
  id: string;
  complaint_type: string;
  description: string;
  location: string | null;
  status: string;
  created_at: string;
}

const NAVY: [number, number, number] = [23, 42, 84];
const GREY: [number, number, number] = [110, 118, 132];

const statusLabel = (status: string) =>
  ({ pending: "Pending", in_progress: "In Progress", resolved: "Resolved", withdrawn: "Withdrawn" } as Record<string, string>)[status] ||
  status;

const title = (s: string) => s.replace(/[-_]/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());

function buildComplaintPdf(
  complaints: ComplaintReportItem[],
  meta: { name?: string | null; email?: string | null },
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = 0;

  const header = () => {
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, pageW, 72, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("E-COMPLAINT", margin, 34);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Complaint Status Report", margin, 52);
    doc.setTextColor(0, 0, 0);
    y = 104;
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - 56) {
      doc.addPage();
      header();
    }
  };

  header();

  doc.setFontSize(10);
  doc.setTextColor(...GREY);
  const generated = new Date().toLocaleString();
  doc.text(`Generated: ${generated}`, margin, y);
  y += 14;
  if (meta.name) { doc.text(`Complainant: ${meta.name}`, margin, y); y += 14; }
  if (meta.email) { doc.text(`Email: ${meta.email}`, margin, y); y += 14; }
  doc.text(`Total complaints: ${complaints.length}`, margin, y);
  y += 22;
  doc.setDrawColor(220, 224, 230);
  doc.line(margin, y, pageW - margin, y);
  y += 24;

  complaints.forEach((c, i) => {
    const descLines = doc.splitTextToSize(c.description || "-", pageW - margin * 2 - 24);
    ensureSpace(96 + descLines.length * 13);

    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`${i + 1}. ${title(c.complaint_type)}`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text(statusLabel(c.status), pageW - margin, y, { align: "right" });
    y += 16;

    doc.setTextColor(60, 66, 78);
    doc.text(`Reference: ${c.id}`, margin + 12, y); y += 13;
    doc.text(`Filed on: ${new Date(c.created_at).toLocaleString()}`, margin + 12, y); y += 13;
    doc.text(`Location: ${c.location || "Not provided"}`, margin + 12, y); y += 13;
    doc.text("Description:", margin + 12, y); y += 13;
    descLines.forEach((line: string) => {
      ensureSpace(20);
      doc.text(line, margin + 24, y);
      y += 13;
    });
    y += 10;
    doc.setDrawColor(235, 238, 242);
    doc.line(margin, y, pageW - margin, y);
    y += 20;
  });

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(...GREY);
    doc.text("This report is generated by the E-COMPLAINT app for the registered user.", margin, pageH - 28);
    doc.text(`Page ${p} of ${pages}`, pageW - margin, pageH - 28, { align: "right" });
  }

  const stamp = new Date().toISOString().slice(0, 10);
  const fileName = complaints.length === 1 ? `complaint-${complaints[0].id.slice(0, 8)}-${stamp}.pdf` : `my-complaints-${stamp}.pdf`;
  return { doc, fileName };
}

export function generateComplaintPdf(
  complaints: ComplaintReportItem[],
  meta: { name?: string | null; email?: string | null },
) {
  const { doc, fileName } = buildComplaintPdf(complaints, meta);
  doc.save(fileName);
}

export async function shareComplaintPdfToWhatsApp(
  complaints: ComplaintReportItem[],
  meta: { name?: string | null; email?: string | null },
): Promise<"shared" | "downloaded"> {
  const { doc, fileName } = buildComplaintPdf(complaints, meta);
  const blob = doc.output("blob") as Blob;
  const file = new File([blob], fileName, { type: "application/pdf" });
  const text =
    complaints.length === 1
      ? `E-COMPLAINT report: ${title(complaints[0].complaint_type)} — status ${statusLabel(complaints[0].status)}`
      : `E-COMPLAINT report: ${complaints.length} complaints with current status`;

  const nav = navigator as Navigator & { canShare?: (data: ShareData) => boolean };
  if (nav.share && nav.canShare?.({ files: [file] })) {
    try {
      await nav.share({ files: [file], title: "E-COMPLAINT report", text });
      return "shared";
    } catch (e) {
      if ((e as DOMException)?.name === "AbortError") return "shared";
    }
  }

  // Fallback: download the PDF and open WhatsApp with a prefilled message to attach it.
  doc.save(fileName);
  window.open(`https://wa.me/?text=${encodeURIComponent(`${text}\n(PDF report downloaded as ${fileName} — attach it here)`)}`, "_blank");
  return "downloaded";
}

export function complaintsToCsv(complaints: ComplaintReportItem[]) {
  const esc = (v: string) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const rows = [
    ["Reference ID", "Complaint Type", "Status", "Filed On", "Location", "Description"],
    ...complaints.map((c) => [
      c.id,
      title(c.complaint_type),
      statusLabel(c.status),
      new Date(c.created_at).toLocaleString(),
      c.location || "",
      (c.description || "").replace(/\r?\n/g, " "),
    ]),
  ];
  const csv = "\uFEFF" + rows.map((r) => r.map(esc).join(",")).join("\r\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8;" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `my-complaints-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
