import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "hi" | "te";

const translations = {
  en: {
    // Index
    appName: "SafeGuard",
    tagline: "Your Safety, Our Priority",
    heroDesc: "Report crimes, access emergency services, and get help — all in one app.",
    welcome: "Welcome",
    logout: "Logout",
    fileComplaint: "File Complaint",
    reportIncident: "Report an incident",
    sosEmergency: "SOS Emergency",
    instantAlert: "Instant alert",
    nearbyStations: "Nearby Stations",
    findPoliceHelp: "Find police help",
    nearbyHospitals: "Nearby Hospitals",
    findMedicalHelp: "Find medical help",
    myComplaints: "My Complaints",
    trackStatus: "Track status",
    emergencyCall: "Emergency Call",
    quickDial: "Quick dial",
    getStarted: "Get Started",
    alreadyHaveAccount: "Already have an account?",
    login: "Login",

    // Auth
    createAccount: "Create Account",
    signUpDesc: "Sign up to report incidents and get help",
    fullName: "Full Name",
    fullNamePlaceholder: "Your full name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    passwordPlaceholder: "Min 6 characters",
    signUp: "Sign Up",
    creating: "Creating...",
    dontHaveAccount: "Don't have an account?",
    verifyEmail: "Verify Your Email",
    verifyEmailDesc: "We've sent a verification link to",
    verifyEmailAction: "I've verified — Continue to Login",
    verifyPhone: "Verify Phone Number",
    verifyPhoneDesc: "Add your phone number for emergency alerts",
    phoneNumber: "Phone Number",
    sendOtp: "Send OTP",
    sendingOtp: "Sending OTP...",
    skipForNow: "Skip for now",
    enterOtp: "Enter OTP",
    enterOtpDesc: "Enter the 6-digit code sent to",
    verifyAndContinue: "Verify & Continue",
    verifying: "Verifying...",
    resendOtp: "Resend OTP",
    welcomeBack: "Welcome Back",
    loginDesc: "Log in to your SafeGuard account",
    yourPassword: "Your password",
    loggingIn: "Logging in...",

    // File Complaint
    crimeType: "Type of Crime *",
    selectCrimeType: "Select crime type",
    location: "Location",
    enterLocation: "Enter or detect location",
    description: "Description *",
    describeIncident: "Describe the incident in detail...",
    evidence: "Evidence (optional)",
    uploadEvidence: "Upload photos or documents",
    submitComplaint: "Submit Complaint",
    submitting: "Submitting...",
    complaintFiled: "Complaint Filed",
    complaintFiledDesc: "Your complaint has been submitted successfully. You can track it in My Complaints.",
    viewMyComplaints: "View My Complaints",
    theft: "Theft / Robbery",
    assault: "Assault",
    fraud: "Fraud / Cybercrime",
    harassment: "Harassment",
    domesticViolence: "Domestic Violence",
    missingPerson: "Missing Person",
    other: "Other",

    // My Complaints
    trackComplaints: "Track your filed complaints",
    noComplaints: "No complaints filed yet",
    pending: "Pending",
    inProgress: "In Progress",
    resolved: "Resolved",

    // SOS
    getImmediateHelp: "Get immediate help",
    sosDesc: "Press the SOS button to send an emergency alert with your live location to nearby authorities and your emergency contacts.",
    tapForHelp: "Tap for help",
    police: "Police (100)",
    ambulance: "Ambulance (108)",
    women: "Women (181)",
    alertSent: "Alert Sent!",
    alertSentDesc: "Your emergency alert has been sent to nearby authorities and your emergency contacts. Help is on the way.",
    liveLocationShared: "Live location shared",
    updatingLocation: "Updating every 30 seconds",
    contactsNotified: "3 emergency contacts notified",
    viaSms: "Via SMS and app notification",
    cancelAlert: "Cancel Alert",

    // Nearby
    policeStationsNearYou: "Police stations near you",
    hospitalsNearYou: "Hospitals & clinics near you",
    locationRequired: "Location Access Required",
    enableLocationPolice: "Please enable location access to find nearby police stations.",
    enableLocationHospital: "Enable location access to find nearby hospitals.",
    tryAgain: "Try Again",
    detectingLocation: "Detecting your location...",
    yourLocation: "Your location",
    findingStations: "Finding nearby stations...",
    findingHospitals: "Finding nearby hospitals...",
    noStationsFound: "No police stations found nearby",
    noHospitalsFound: "No hospitals or clinics found nearby",
    stationsFound: "Police Stations Found",
    hospitalsFound: "Hospitals & Clinics Found",
    tapToSeeRoute: "Tap to see route",
    searchStations: "Search police stations...",
    searchHospitals: "Search hospitals & clinics...",
    searchLocation: "Search for a location...",
    open: "Open",
    closed: "Closed",
    routeShown: "Route Shown ✓",
    tapForRoute: "Tap for Route",
    walking: "Walking",
    twoWheeler: "Two Wheeler",
    fourWheeler: "Four Wheeler",
    openInGoogleMaps: "Open in Google Maps",
    hospital: "Hospital",
    clinic: "Clinic",
    findNearbyStations: "Find Nearby Stations",
    findNearbyHospitals: "Find Nearby Hospitals",
    locationFallbackNote: "If location is unavailable, we'll show results for Delhi",
    hideSteps: "Hide Steps",
    showSteps: "Show Steps",
    selectCity: "Select a city",
    useMyLocation: "Use my location",
    showingResultsFor: "Showing results for",
  },
  hi: {
    appName: "सेफगार्ड",
    tagline: "आपकी सुरक्षा, हमारी प्राथमिकता",
    heroDesc: "अपराध की रिपोर्ट करें, आपातकालीन सेवाओं तक पहुंचें, और सहायता प्राप्त करें — सब एक ऐप में।",
    welcome: "स्वागत है",
    logout: "लॉगआउट",
    fileComplaint: "शिकायत दर्ज करें",
    reportIncident: "घटना की रिपोर्ट करें",
    sosEmergency: "SOS आपातकाल",
    instantAlert: "तत्काल अलर्ट",
    nearbyStations: "नजदीकी थाने",
    findPoliceHelp: "पुलिस सहायता खोजें",
    nearbyHospitals: "नजदीकी अस्पताल",
    findMedicalHelp: "चिकित्सा सहायता खोजें",
    myComplaints: "मेरी शिकायतें",
    trackStatus: "स्थिति ट्रैक करें",
    emergencyCall: "आपातकालीन कॉल",
    quickDial: "त्वरित डायल",
    getStarted: "शुरू करें",
    alreadyHaveAccount: "पहले से खाता है?",
    login: "लॉगिन",

    createAccount: "खाता बनाएं",
    signUpDesc: "घटनाओं की रिपोर्ट करने और सहायता प्राप्त करने के लिए साइन अप करें",
    fullName: "पूरा नाम",
    fullNamePlaceholder: "आपका पूरा नाम",
    email: "ईमेल",
    emailPlaceholder: "you@example.com",
    password: "पासवर्ड",
    passwordPlaceholder: "न्यूनतम 6 अक्षर",
    signUp: "साइन अप",
    creating: "बना रहे हैं...",
    dontHaveAccount: "खाता नहीं है?",
    verifyEmail: "अपना ईमेल सत्यापित करें",
    verifyEmailDesc: "हमने एक सत्यापन लिंक भेजा है",
    verifyEmailAction: "मैंने सत्यापित किया — लॉगिन जारी रखें",
    verifyPhone: "फोन नंबर सत्यापित करें",
    verifyPhoneDesc: "आपातकालीन अलर्ट के लिए अपना फोन नंबर जोड़ें",
    phoneNumber: "फोन नंबर",
    sendOtp: "OTP भेजें",
    sendingOtp: "OTP भेज रहे हैं...",
    skipForNow: "अभी के लिए छोड़ें",
    enterOtp: "OTP दर्ज करें",
    enterOtpDesc: "भेजा गया 6-अंकीय कोड दर्ज करें",
    verifyAndContinue: "सत्यापित करें और जारी रखें",
    verifying: "सत्यापित कर रहे हैं...",
    resendOtp: "OTP पुनः भेजें",
    welcomeBack: "वापस स्वागत है",
    loginDesc: "अपने सेफगार्ड खाते में लॉगिन करें",
    yourPassword: "आपका पासवर्ड",
    loggingIn: "लॉगिन हो रहा है...",

    crimeType: "अपराध का प्रकार *",
    selectCrimeType: "अपराध प्रकार चुनें",
    location: "स्थान",
    enterLocation: "स्थान दर्ज करें या पता लगाएं",
    description: "विवरण *",
    describeIncident: "घटना का विस्तार से वर्णन करें...",
    evidence: "साक्ष्य (वैकल्पिक)",
    uploadEvidence: "फोटो या दस्तावेज अपलोड करें",
    submitComplaint: "शिकायत जमा करें",
    submitting: "जमा हो रहा है...",
    complaintFiled: "शिकायत दर्ज हो गई",
    complaintFiledDesc: "आपकी शिकायत सफलतापूर्वक जमा हो गई है। आप इसे मेरी शिकायतों में ट्रैक कर सकते हैं।",
    viewMyComplaints: "मेरी शिकायतें देखें",
    theft: "चोरी / लूट",
    assault: "हमला",
    fraud: "धोखाधड़ी / साइबर अपराध",
    harassment: "उत्पीड़न",
    domesticViolence: "घरेलू हिंसा",
    missingPerson: "लापता व्यक्ति",
    other: "अन्य",

    trackComplaints: "अपनी दर्ज शिकायतों को ट्रैक करें",
    noComplaints: "अभी तक कोई शिकायत दर्ज नहीं",
    pending: "लंबित",
    inProgress: "प्रगति में",
    resolved: "हल हो गया",

    getImmediateHelp: "तुरंत सहायता प्राप्त करें",
    sosDesc: "आपातकालीन अलर्ट भेजने के लिए SOS बटन दबाएं। आपका लाइव स्थान नजदीकी अधिकारियों और आपके आपातकालीन संपर्कों को भेजा जाएगा।",
    tapForHelp: "सहायता के लिए टैप करें",
    police: "पुलिस (100)",
    ambulance: "एम्बुलेंस (108)",
    women: "महिला (181)",
    alertSent: "अलर्ट भेजा गया!",
    alertSentDesc: "आपका आपातकालीन अलर्ट नजदीकी अधिकारियों और आपके आपातकालीन संपर्कों को भेजा गया है। सहायता रास्ते में है।",
    liveLocationShared: "लाइव स्थान साझा किया गया",
    updatingLocation: "हर 30 सेकंड में अपडेट हो रहा है",
    contactsNotified: "3 आपातकालीन संपर्कों को सूचित किया गया",
    viaSms: "SMS और ऐप नोटिफिकेशन द्वारा",
    cancelAlert: "अलर्ट रद्द करें",

    policeStationsNearYou: "आपके पास पुलिस थाने",
    hospitalsNearYou: "आपके पास अस्पताल और क्लिनिक",
    locationRequired: "स्थान अनुमति आवश्यक",
    enableLocationPolice: "नजदीकी पुलिस थाने खोजने के लिए कृपया स्थान अनुमति दें।",
    enableLocationHospital: "नजदीकी अस्पताल खोजने के लिए स्थान अनुमति दें।",
    tryAgain: "पुनः प्रयास करें",
    detectingLocation: "आपका स्थान पता लगा रहे हैं...",
    yourLocation: "आपका स्थान",
    findingStations: "नजदीकी थाने खोज रहे हैं...",
    findingHospitals: "नजदीकी अस्पताल खोज रहे हैं...",
    noStationsFound: "नजदीक कोई पुलिस थाना नहीं मिला",
    noHospitalsFound: "नजदीक कोई अस्पताल या क्लिनिक नहीं मिला",
    stationsFound: "पुलिस थाने मिले",
    hospitalsFound: "अस्पताल और क्लिनिक मिले",
    tapToSeeRoute: "मार्ग देखने के लिए टैप करें",
    searchStations: "पुलिस थाने खोजें...",
    searchHospitals: "अस्पताल और क्लिनिक खोजें...",
    searchLocation: "स्थान खोजें...",
    open: "खुला",
    closed: "बंद",
    routeShown: "मार्ग दिखाया ✓",
    tapForRoute: "मार्ग के लिए टैप करें",
    walking: "पैदल",
    twoWheeler: "दोपहिया",
    fourWheeler: "चारपहिया",
    openInGoogleMaps: "Google Maps में खोलें",
    hospital: "अस्पताल",
    clinic: "क्लिनिक",
    findNearbyStations: "नजदीकी थाने खोजें",
    findNearbyHospitals: "नजदीकी अस्पताल खोजें",
    locationFallbackNote: "यदि स्थान उपलब्ध नहीं है, तो हम दिल्ली के परिणाम दिखाएंगे",
    hideSteps: "चरण छिपाएं",
    showSteps: "चरण दिखाएं",
    selectCity: "शहर चुनें",
    useMyLocation: "मेरा स्थान उपयोग करें",
    showingResultsFor: "परिणाम दिखा रहे हैं",
  },
  te: {
    appName: "సేఫ్‌గార్డ్",
    tagline: "మీ భద్రత, మా ప్రాధాన్యత",
    heroDesc: "నేరాలను నివేదించండి, అత్యవసర సేవలను పొందండి మరియు సహాయం పొందండి — అన్నీ ఒకే యాప్‌లో.",
    welcome: "స్వాగతం",
    logout: "లాగ్అవుట్",
    fileComplaint: "ఫిర్యాదు చేయండి",
    reportIncident: "సంఘటనను నివేదించండి",
    sosEmergency: "SOS అత్యవసరం",
    instantAlert: "తక్షణ హెచ్చరిక",
    nearbyStations: "సమీపంలోని స్టేషన్లు",
    findPoliceHelp: "పోలీసు సహాయం కనుగొనండి",
    nearbyHospitals: "సమీపంలోని ఆసుపత్రులు",
    findMedicalHelp: "వైద్య సహాయం కనుగొనండి",
    myComplaints: "నా ఫిర్యాదులు",
    trackStatus: "స్థితిని ట్రాక్ చేయండి",
    emergencyCall: "అత్యవసర కాల్",
    quickDial: "త్వరిత డయల్",
    getStarted: "ప్రారంభించండి",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    login: "లాగిన్",

    createAccount: "ఖాతా సృష్టించండి",
    signUpDesc: "సంఘటనలను నివేదించడానికి మరియు సహాయం పొందడానికి సైన్ అప్ చేయండి",
    fullName: "పూర్తి పేరు",
    fullNamePlaceholder: "మీ పూర్తి పేరు",
    email: "ఇమెయిల్",
    emailPlaceholder: "you@example.com",
    password: "పాస్‌వర్డ్",
    passwordPlaceholder: "కనీసం 6 అక్షరాలు",
    signUp: "సైన్ అప్",
    creating: "సృష్టిస్తోంది...",
    dontHaveAccount: "ఖాతా లేదా?",
    verifyEmail: "మీ ఇమెయిల్‌ను ధృవీకరించండి",
    verifyEmailDesc: "మేము ధృవీకరణ లింక్ పంపాము",
    verifyEmailAction: "నేను ధృవీకరించాను — లాగిన్ కొనసాగించండి",
    verifyPhone: "ఫోన్ నంబర్ ధృవీకరించండి",
    verifyPhoneDesc: "అత్యవసర హెచ్చరికల కోసం మీ ఫోన్ నంబర్ జోడించండి",
    phoneNumber: "ఫోన్ నంబర్",
    sendOtp: "OTP పంపండి",
    sendingOtp: "OTP పంపుతోంది...",
    skipForNow: "ప్రస్తుతానికి దాటవేయండి",
    enterOtp: "OTP నమోదు చేయండి",
    enterOtpDesc: "పంపిన 6-అంకెల కోడ్ నమోదు చేయండి",
    verifyAndContinue: "ధృవీకరించి కొనసాగించండి",
    verifying: "ధృవీకరిస్తోంది...",
    resendOtp: "OTP మళ్ళీ పంపండి",
    welcomeBack: "తిరిగి స్వాగతం",
    loginDesc: "మీ సేఫ్‌గార్డ్ ఖాతాలో లాగిన్ అవ్వండి",
    yourPassword: "మీ పాస్‌వర్డ్",
    loggingIn: "లాగిన్ అవుతోంది...",

    crimeType: "నేర రకం *",
    selectCrimeType: "నేర రకాన్ని ఎంచుకోండి",
    location: "స్థానం",
    enterLocation: "స్థానం నమోదు చేయండి లేదా గుర్తించండి",
    description: "వివరణ *",
    describeIncident: "సంఘటనను వివరంగా వర్ణించండి...",
    evidence: "సాక్ష్యం (ఐచ్ఛికం)",
    uploadEvidence: "ఫోటోలు లేదా పత్రాలు అప్‌లోడ్ చేయండి",
    submitComplaint: "ఫిర్యాదు సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    complaintFiled: "ఫిర్యాదు నమోదైంది",
    complaintFiledDesc: "మీ ఫిర్యాదు విజయవంతంగా సమర్పించబడింది. మీరు నా ఫిర్యాదులలో ట్రాక్ చేయవచ్చు.",
    viewMyComplaints: "నా ఫిర్యాదులు చూడండి",
    theft: "దొంగతనం / దోపిడీ",
    assault: "దాడి",
    fraud: "మోసం / సైబర్ నేరం",
    harassment: "వేధింపు",
    domesticViolence: "గృహ హింస",
    missingPerson: "తప్పిపోయిన వ్యక్తి",
    other: "ఇతరం",

    trackComplaints: "మీ నమోదైన ఫిర్యాదులను ట్రాక్ చేయండి",
    noComplaints: "ఇంకా ఫిర్యాదులు నమోదు కాలేదు",
    pending: "పెండింగ్",
    inProgress: "ప్రగతిలో ఉంది",
    resolved: "పరిష్కరించబడింది",

    getImmediateHelp: "తక్షణ సహాయం పొందండి",
    sosDesc: "అత్యవసర హెచ్చరిక పంపడానికి SOS బటన్ నొక్కండి. మీ లైవ్ స్థానం సమీపంలోని అధికారులకు మరియు మీ అత్యవసర పరిచయాలకు పంపబడుతుంది.",
    tapForHelp: "సహాయం కోసం టాప్ చేయండి",
    police: "పోలీసు (100)",
    ambulance: "అంబులెన్స్ (108)",
    women: "మహిళ (181)",
    alertSent: "హెచ్చరిక పంపబడింది!",
    alertSentDesc: "మీ అత్యవసర హెచ్చరిక సమీపంలోని అధికారులకు మరియు మీ అత్యవసర పరిచయాలకు పంపబడింది. సహాయం మార్గంలో ఉంది.",
    liveLocationShared: "లైవ్ స్థానం భాగస్వామ్యం చేయబడింది",
    updatingLocation: "ప్రతి 30 సెకన్లకు అప్‌డేట్ అవుతోంది",
    contactsNotified: "3 అత్యవసర పరిచయాలకు తెలియజేయబడింది",
    viaSms: "SMS మరియు యాప్ నోటిఫికేషన్ ద్వారా",
    cancelAlert: "హెచ్చరిక రద్దు చేయండి",

    policeStationsNearYou: "మీ సమీపంలో పోలీస్ స్టేషన్లు",
    hospitalsNearYou: "మీ సమీపంలో ఆసుపత్రులు & క్లినిక్‌లు",
    locationRequired: "స్థాన అనుమతి అవసరం",
    enableLocationPolice: "సమీపంలోని పోలీస్ స్టేషన్లను కనుగొనడానికి దయచేసి స్థాన అనుమతిని ఆన్ చేయండి.",
    enableLocationHospital: "సమీపంలోని ఆసుపత్రులను కనుగొనడానికి స్థాన అనుమతిని ఆన్ చేయండి.",
    tryAgain: "మళ్ళీ ప్రయత్నించండి",
    detectingLocation: "మీ స్థానం గుర్తిస్తోంది...",
    yourLocation: "మీ స్థానం",
    findingStations: "సమీపంలోని స్టేషన్లు వెతుకుతోంది...",
    findingHospitals: "సమీపంలోని ఆసుపత్రులు వెతుకుతోంది...",
    noStationsFound: "సమీపంలో పోలీస్ స్టేషన్లు కనుగొనబడలేదు",
    noHospitalsFound: "సమీపంలో ఆసుపత్రులు లేదా క్లినిక్‌లు కనుగొనబడలేదు",
    stationsFound: "పోలీస్ స్టేషన్లు కనుగొనబడ్డాయి",
    hospitalsFound: "ఆసుపత్రులు & క్లినిక్‌లు కనుగొనబడ్డాయి",
    tapToSeeRoute: "మార్గం చూడటానికి టాప్ చేయండి",
    searchStations: "పోలీస్ స్టేషన్లు వెతకండి...",
    searchHospitals: "ఆసుపత్రులు & క్లినిక్‌లు వెతకండి...",
    searchLocation: "ప్రదేశాన్ని వెతకండి...",
    open: "తెరిచి ఉంది",
    closed: "మూసి ఉంది",
    routeShown: "మార్గం చూపబడింది ✓",
    tapForRoute: "మార్గం కోసం టాప్ చేయండి",
    walking: "నడక",
    twoWheeler: "ద్విచక్ర వాహనం",
    fourWheeler: "కారు",
    openInGoogleMaps: "Google Maps లో తెరవండి",
    hospital: "ఆసుపత్రి",
    clinic: "క్లినిక్",
    findNearbyStations: "సమీపంలోని స్టేషన్లు కనుగొనండి",
    findNearbyHospitals: "సమీపంలోని ఆసుపత్రులు కనుగొనండి",
    locationFallbackNote: "స్థానం అందుబాటులో లేకుంటే, ఢిల్లీ ఫలితాలు చూపిస్తాము",
    hideSteps: "దశలు దాచు",
    showSteps: "దశలు చూపు",
    selectCity: "నగరాన్ని ఎంచుకోండి",
    useMyLocation: "నా స్థానాన్ని ఉపయోగించండి",
    showingResultsFor: "ఫలితాలు చూపిస్తోంది",
  },
} as const;

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: TranslationKeys): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
